version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - net

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./app/.env
    depends_on:
      - server
    networks:
      - net

networks:
  net:
    driver: bridge
