version: "3.7"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # redis:

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  redis:
    driver: local
